# pyproject.toml
target-version = "py312"

[tool.black]
target-version = ["py312"]
line-length = 100

[tool.ruff]
# Enable Pyflakes `E` and `F` codes by default.
lint.select = ["E", "F"]

[tool.hatch.build.targets.wheel]
macos-max-compat = true
