# Generated by Django 5.0.6 on 2024-06-26 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("preferred_name", models.CharField(blank=True, max_length=50)),
                ("stripe_customer_id", models.CharField(blank=True, max_length=50, null=True)),
                ("stripe_subscription_id", models.CharField(blank=True, max_length=50, null=True)),
                ("card_last4", models.CharField(blank=True, max_length=4, null=True)),
                ("card_exp_month", models.IntegerField(blank=True, null=True)),
                ("card_exp_year", models.IntegerField(blank=True, null=True)),
                (
                    "card_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Visa", "Visa"),
                            ("MasterCard", "MasterCard"),
                            ("Amex", "American Express"),
                            ("Discover", "Discover"),
                            ("Diners", "Diners Club"),
                            ("JCB", "JCB"),
                        ],
                        default="Visa",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("FRE", "Free"), ("PRE", "Premium")], default="FRE", max_length=3
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
