branch-defaults:
  add-github-action:
    environment: digibooks-backend-dev
    group_suffix: null
  add-log-out:
    environment: digibooks-backend-dev
    group_suffix: null
global:
  application_name: digibooks-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: novabrains
  repository: null
  sc: git
  workspace_type: Application
