#name: Notify members of PR
#on:
#  pull_request:
#    types:
#      - review_requested
#jobs:
#  amhajja_notify:
#    runs-on: ubuntu-latest
#    if: ${{ github.event.requested_reviewer.login == 'amhajja'}}
#    steps:
#      - name: "Sending SMS Notification to amhajja"
#        uses: twilio-labs/actions-sms@v1
#        with:
#          fromPhoneNumber: ${{ secrets.SENDER_NUMBER }}
#          toPhoneNumber: ${{ secrets.AMHAJJA_PHONE_NUMBER }}
#          message: "PR review requested: ${{github.event.pull_request.title}}"
#        env:
#          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
#          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
#          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
#  austinjhunt_notify:
#    runs-on: ubuntu-latest
#    if: ${{ github.event.requested_reviewer.login == 'austinjhunt'}}
#    steps:
#      - name: "Sending SMS Notification to austinjhunt"
#        uses: twilio-labs/actions-sms@v1
#        with:
#          fromPhoneNumber: ${{ secrets.SENDER_NUMBER }}
#          toPhoneNumber: ${{ secrets.AUSTINJHUNT_PHONE_NUMBER }}
#          message: "PR review requested: ${{github.event.pull_request.title}}"
#        env:
#          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
#          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
#          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
